name: Request PR Review and Notify Slack

on:
  pull_request:
    types: [opened]

jobs:
  request-copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from Copilot
        env:
          # Menggunakan secret token classic yang baru Anda buat
          GH_TOKEN: ${{ secrets.GH_PAT_CLASSIC }}
          
          # Variabel ini diambil secara otomatis oleh GitHub Actions
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/pulls/$PR_NUMBER/requested_reviewers" \
            -f reviewers[]=copilot-pull-request-reviewer

  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "🚀 New Pull Request"
          SLACK_MESSAGE: |
            A new PR was opened by *@${{ github.actor }}* and a review was requested from Copilot.
            *<${{ github.event.pull_request.html_url }}|View Pull Request>*
          SLACK_COLOR: '#007ec6'